### ISSUE TITLE
Insert reverse topics order to MoodleBooster Dashboard

### ISSUE THREAD

**Issue by norbit8** [norbit8/MoodleBooster#101]
## What?

Insert the button of "reverse topics order" to MoodleBoosters Dashboard.

## Why?

To be more orginazied and, because the dashboard is currently empty while it's whole purpose is to include features like this.

<img width="794" alt="Screen Shot 2021-06-21 at 11 47 43" src="https://user-images.githubusercontent.com/18491183/122734295-9dcf6f00-d286-11eb-9deb-1320691eabd5.png">

**Comment by idan2468** [comment]
In my opinion, the course dashboard has to be only on moodle's main page.
It should show some general information to the user, maybe like assignments due dates and more...
Do you think it should be in more places?

see issue #97 for more details

**Comment by yanirelfasy** [comment]
@idan2468 I agree with you, in addition, as you mentioned, the dashboard panel is visible in the login screen which makes it look like a bug

**Comment by idan2468** [comment]
> @idan2468 I agree with you, in addition, as you mentioned, the dashboard panel is visible in the login screen which makes it look like a bug

Agree..

**Comment by norbit8** [comment]
Yes, in a second thought you're right.
