### ISSUE TITLE
Important refactoring

### ISSUE THREAD

**Issue by idan2468** [norbit8/MoodleBooster#111]
Few important changes...

1.  Messaging to storageLoader: I've changed the messaging functionality to take some structure (redux like) with action and payload
2. Now we get the course Id for course remover through the id query parameter of the course's link (safer)
3. Changed values of monochrome and dark mode to be boolean instead of on/off
4. did some code splitting by extracting some scopes to functions

Now the codebase looks way better to me, for anyone that wants further explanation you can ping me.

**Comment by yanirelfasy** [comment]
Fixed at #112
