### ISSUE TITLE
Reverse topics order appears at main screen at chrome but not at firefox  

### ISSUE THREAD

**Issue by liron58** [norbit8/MoodleBooster#125]
In chrome this button appears even though it has no effect on the dom .
![image](https://user-images.githubusercontent.com/28891740/123419927-80bad900-d5c3-11eb-9e8d-09da963d898c.png)
On firefox the beahviour is correct and the button appears only where is effective.
![image](https://user-images.githubusercontent.com/28891740/123419984-96c89980-d5c3-11eb-8b3f-5eb4d20e4f37.png)

**Comment by norbit8** [comment]
This problem was fixed on #116 PR.
