### ISSUE TITLE
tried to create a pull request , returned permission denied

### ISSUE THREAD

**Issue by DanielSaroussy** [norbit8/MoodleBooster#28]
Hi!
I tried to make a pull request for a READM update, but when I tried to push changes after fork, new branch,  and commit went fine, the push command returned the following : 
"remote: Permission to norbit8/MoodleBooster.git denied to DanielSaroussy.
fatal: unable to access 'https://github.com/norbit8/MoodleBooster/': The requested URL returned error: 403"
I have made pull requests to other projects the same way so I wonder if it has something to do with settings. 
Thank you. 
Daniel

**Comment by norbit8** [comment]
Hey Daniel,

So we've already got 2 pull requests, and our settings are fine.
It does sound like you've done everything right, but just to make sure please:

1. fork the repo
**2. clone the forked repo**
3. create new branch (don't work on master branch)
4. add, commit & push.

Anyways thank you for trying.

**Comment by DanielSaroussy** [comment]
> Hey Daniel,
> 
> So we've already got 2 pull requests, and our settings are fine.
> It does sound like you've done everything right, but just to make sure please:
> 
> 1. fork the repo
>    **2. clone the forked repo**
> 2. create new branch (don't work on master branch)
> 3. add, commit & push.
> 
> Anyways thank you for trying.

Hi
These are the commands 
1. git clone <your project URL> 
2. git checkout -b new_branch
3. git remote add upstream <your project URL>
--changed readme-- 
4. git add --all 
5. git commit -m "message" 
6.  git push -u origin new_branch
!!error!!

anything you can put your finger on as wring maybe?
Thank you (:

**Comment by DanielSaroussy** [comment]
> > Hey Daniel,
> > So we've already got 2 pull requests, and our settings are fine.
> > It does sound like you've done everything right, but just to make sure please:
> > 
> > 1. fork the repo
> >    **2. clone the forked repo**
> > 2. create new branch (don't work on master branch)
> > 3. add, commit & push.
> > 
> > Anyways thank you for trying.
> 
> Hi
> These are the commands
> 
> 1. git clone
> 2. git checkout -b new_branch
> 3. git remote add upstream 
>    --changed readme--
> 4. git add --all
> 5. git commit -m "message"
> 6. git push -u origin new_branch
>    !!error!!
> 
> anything you can put your finger on as wring maybe?
> Thank you (:

Ok now I see you said to clone the fork, it worked fine the way I mentioned, Ill try again

**Comment by norbit8** [comment]
Oh and after you push, you should go to the forked repo, and you should have a button named "pull request" (green button), press it, and you'll see what to do.

(I see your branch on your forked repo)

**Comment by norbit8** [comment]
Nice you got it! 🥇
