### ISSUE TITLE
Add more levels of freedom to the font size slider

### ISSUE THREAD

**Issue by norbit8** [norbit8/MoodleBooster#58]
## What?

Add more levels of freedom to the font size slider in the enhance page.

<img width="454" alt="Screen Shot 2021-06-18 at 19 14 55" src="https://user-images.githubusercontent.com/18491183/122589895-7cde0280-d069-11eb-844c-5b437af3c1cf.png">

## Why?

IMO only 3 levels of freedom is too little, we can have much more levels of freedom, so our users can enjoy a better UI.

**Comment by idan2468** [comment]
Fixed
