### ISSUE TITLE
Slider position inside Enhance Page is not consistent

### ISSUE THREAD

**Issue by yanirelfasy** [norbit8/MoodleBooster#62]
# How to reproduce:
1. Open the MoodleBooster popup
2. Go to Enhance page
3. Change the font size
4. Press the back button
5. Return to Enhance page

# Current Behavior:
The slider returns to the starting point but the the correct position should be as we left it.
position on step 3
![image](https://user-images.githubusercontent.com/24404481/122591740-0e4e7400-d06c-11eb-8034-538549d7ba9a.png)
position on step 5 (notice that the font is bigger
![image](https://user-images.githubusercontent.com/24404481/122591893-43f35d00-d06c-11eb-9de8-44a7f5b268bf.png)

# Expected Behavior:
The slider position should fit the page state everytime.

**Comment by idan2468** [comment]
Fixed
