### ISSUE TITLE
Contrast doesn't save when font size is changed

### ISSUE THREAD

**Issue by guys1915** [norbit8/MoodleBooster#70]
# How to reproduce:
1. Open MoodleBooster
2. Go to Enhance page
3. Move contrast slider
4. Move font size slider

# Current behaviour:
When moving the contrast slider the contrast changes:
![image](https://user-images.githubusercontent.com/66463385/122639435-810a2e80-d102-11eb-93cc-8ab188b299eb.png)

But when moving the font size slider the contrast set earlier is not saved:
![image](https://user-images.githubusercontent.com/66463385/122639450-9aab7600-d102-11eb-9a74-af219e6e204d.png)

# Expected behavior:
Contrast and font size should be saved once the slider is moved.

**Comment by yanirelfasy** [comment]
Fixed at #110
