### ISSUE TITLE
MoodleBooster Dashboard Container

### ISSUE THREAD

**Issue by tamiror6** [norbit8/MoodleBooster#80]
### **What?**
Out ream is growing , and more and more ideas come and go, our vision is to make the experience with moodle booster as more comfortable as we can.
We want the option to integrate insights and alerts in a **Moodle Booster Dashboard!!**

### **Current Behavior**
Doesn't exist.

### **Expected Behavior**
<img width="1562" alt="Screen Shot 2021-06-19 at 15 37 19" src="https://user-images.githubusercontent.com/76107540/122642722-84a6b100-d114-11eb-99a3-c06f5e914882.png">

**Comment by norbit8** [comment]
I agree but we should release this feature once we have some content to put there, do you have any suggestions for now?
