### ISSUE TITLE
Can't add label when opening an issue.

### ISSUE THREAD

**Issue by ori-frenkel** [norbit8/MoodleBooster#82]
Cant add label to issue.

![image](https://user-images.githubusercontent.com/49747014/122643273-99387880-d117-11eb-9690-684507e5f2e4.png)

**Comment by norbit8** [comment]
This ability is only available for contributors.
See [this](https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner/13829505#13829505) highly upvoted SO post.

Suggestion: add '[bug/feat]' tag to the PR title and the maintainers will tag that for you.
